spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
